// react-todo/src/components/TodoItem.js
import React, { Component } from 'react';
import Checkbox from './Checkbox';
import Button from './Button';

class TodoItem extends Component {
  render() {
    return (
      <div class="Todo__item view">
        <div class="col">
          <Checkbox 
            fieldName="todo[completed]"
            checked={ this.props.todo.completed }
          />
        </div>
        <div class="col">
          { this.props.todo.title }
        </div>
        <div class="col">
          <Button text="Delete" />
        </div>
      </div>
    );
  }
}

export default TodoItem;

// vue/src/components/TodoItem.vue
<template>
  <li class="todo__item">
    <div class="col">
      <div class="form-check">
        <input 
          type="checkbox"
          class="form-check-input"
          v-model="todo.completed"
        >
      </div>
    </div>
    <div class="col">
      {{ todo.task }}
    </div>
    <div class="col">
      <button
        v-on:click="$emit('delete-todo', todo)"
        class="btn btn-secondary"
      >
        Remove
      </button>
    </div>
  </li>
</template>

<script>
export default {
  name: "TodoItem",

  props: ['todo']
}
</script>
